config/routes.rb
Rails.application.routes.draw do
  get '/new', to: 'games#new', as: :new
  post '/score', to: 'games#score', as: :score
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'net/http'
require 'json'

class GamesController < ApplicationController
  def new
    alphabet = ('a'..'z').to_a
    @letters = Array.new(10) { alphabet.sample }
    session[:letters] = @letters.map(&:downcase)
  end

  def score
    word = params[:word].gsub(/[^A-Za-z]/, '').downcase
    @letters = session[:letters].map(&:downcase)
    letters_match = word.chars.all? { |letter| @letters.include?(letter) }

    if letters_match
      if valid_word?(word)
        @message = "Congratulations! '#{word}' is a valid word."
        @score = word.length
      else
        @message = "Sorry, '#{word}' is not a valid English word."
        @score = 0
      end
    else
      @message = "Sorry, '#{word}' can't be built from the given letters."
      @score = 0
    end
  end

  private

  def valid_word?(word)
    uri = URI.parse("https://wagon-dictionary.herokuapp.com/#{word}")
    http = Net::HTTP.new(uri.host, uri.port)
    http.open_timeout = 10 # Increase the timeout value (in seconds) as needed
    http.read_timeout = 10 # Increase the timeout value (in seconds) as needed
    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    response_body = JSON.parse(response.body)
    response_body['found']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>-- New Game --</h1>

<div class="set">
  <% @letters.each do |letter| %>
    <div class="letter">
      <%= letter %>
    </div>
  <% end %>
</div>


<div class="form">
  <form action="<%= score_path %>" method="post" data-turbo="false">
    <label for="word">What is the longest word you can find?</label>
    <input type="text" id="word" name="word" value="<%= params[:word] %>">
    <input type="submit" class="btn btn-secondary" value="Submit">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </form>
</div>

app/views/games/score.html.erb
<div class="container">
  <h1>Game Results</h1>
  <p><strong>Word:</strong> <%= params[:word] %></p>
  <p><strong>Message:</strong> <%= @message %></p>
  <p><strong>Score:</strong> <%= @score %></p>
  <%= link_to "Play again", new_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>